/**
 * Concise tool descriptions written for Qwen Code's model-facing tool list.
 *
 * These are deliberately static. Do not shorten incoming descriptions with
 * substring/slicing logic: doing so previously changed the valid subagent type
 * `general-purpose` into the invalid value `general-purpos`.
 */
const AI_AUTHORED_TOOL_SUMMARIES: Record<string, string> = {
  edit: 'Replace an exact text block in an existing file. Read the file first and provide the precise old and new text.',
  write_file: 'Create a file or replace its complete contents at the requested path.',
  read_file: 'Read a file, optionally selecting a line range with offset and limit.',
  zoom_image: 'Crop or enlarge part of an image so visual details can be inspected.',
  grep_search: 'Search file contents with a text or regular-expression pattern and return matching locations.',
  glob: 'Find files whose paths match a glob pattern.',
  run_shell_command: 'Run a shell command, either to completion or as a managed background process.',
  todo_write: 'Create or update the visible task list, keeping at most one item in progress.',
  save_memory: 'Save a durable user fact or preference for future Qwen Code sessions.',
  agent:
    'Delegate a focused task to a subagent. Set subagent_type to an exact advertised value: general-purpose is the broad default, while fork inherits parent conversation context. Supply a short description and a complete prompt; use run_in_background only when concurrent work is appropriate.',
  skill: 'Load a named skill so its instructions can guide the current task.',
  exit_plan_mode: 'Submit the completed plan and request permission to begin implementation.',
  enter_plan_mode: 'Switch into read-only planning when the user asks for a plan before implementation.',
  web_fetch: 'Retrieve and analyze content from a specific web address.',
  web_search: 'Search the web for current information and source links.',
  image_gen: 'Generate a new image or edit a supplied image from a detailed visual prompt.',
  list_directory: 'List the files and folders directly inside a directory.',
  lsp: 'Query language-server features such as definitions, references, symbols, diagnostics, or hover information.',
  ask_user_question: 'Ask the user a short structured question when a necessary choice cannot be determined safely.',
  cron_create: 'Create a recurring scheduled Qwen Code task from a schedule and prompt.',
  cron_list: 'List configured recurring Qwen Code tasks and their status.',
  cron_delete: 'Delete a recurring Qwen Code task by its identifier.',
  loop_wakeup: 'Schedule the next wake-up for an active autonomous loop.',
  create_sub_session: 'Create an independent Qwen Code sub-session for a separately managed task.',
  list_agents: 'List active subagents or teammates and their current status.',
  task_stop: 'Stop a running background task or subagent by its identifier.',
  task_create: 'Create a trackable task with its description and dependencies.',
  task_update: 'Update the status, owner, description, or dependencies of an existing task.',
  task_list: 'List current tasks, ownership, dependencies, and status.',
  team_create: 'Create a named team for coordinating multiple agents.',
  team_delete: 'Delete the active agent team after its work is finished.',
  team_plan_approval: 'Approve or reject a teammate plan that requires leader review.',
  send_message: 'Send a message to a running subagent or teammate.',
  structured_output: 'Return a final response that conforms to the requested structured schema.',
  monitor: 'Read output or manage a long-running command started in the background.',
  notebook_edit: 'Replace, insert, or delete a cell in a Jupyter notebook.',
  tool_search: 'Discover tools that are not currently loaded and make matching tools available.',
  read_mcp_resource: 'Read a specific resource exposed by an MCP server.',
  enter_worktree: 'Create and enter an isolated Git worktree for changes that must not affect the main checkout.',
  exit_worktree: 'Leave an isolated Git worktree and report or integrate its changes as requested.',
  workflow: 'Run a registered multi-step workflow with the supplied inputs.',
  artifact: 'Create or update a rich artifact using the artifact tool interface.',
  record_artifact: 'Register a generated artifact so it can be presented and tracked.',
  get_goal: 'Read the current persistent goal, status, and remaining budget.',
  update_goal: 'Mark the current persistent goal complete or blocked when its required conditions are met.',
  display_image: 'Display a local image in the main Qwen Code session for visual inspection.',
  computer_use__bring_to_front: 'Activate a target application window before sending foreground input.',
  computer_use__check_for_update: 'Check whether a newer computer-control driver is available without installing it.',
  computer_use__check_permissions: 'Check computer-control permissions and optionally request any missing operating-system grants.',
  computer_use__click: 'Left-click a UI element or window-relative coordinate in a target application.',
  computer_use__double_click: 'Double-click a UI element or coordinate in a target application.',
  computer_use__drag: 'Drag from one window-relative coordinate to another, optionally controlling duration and mouse button.',
  computer_use__end_session: 'End a computer-control session and release its session state.',
  computer_use__get_accessibility_tree: 'Read the accessibility hierarchy for a target application window.',
  computer_use__get_agent_cursor_state: 'Read the current agent-cursor visibility, style, position, and motion settings.',
  computer_use__get_config: 'Read the current computer-control driver configuration.',
  computer_use__get_cursor_position: 'Read the current pointer position.',
  computer_use__get_recording_state: 'Read the status of computer-control trajectory recording.',
  computer_use__get_screen_size: 'Read the dimensions and scale information for available screens.',
  computer_use__get_window_state: 'Capture a target window and its indexed accessible elements for reliable UI interaction.',
  computer_use__hotkey: 'Press a keyboard shortcut in a target application.',
  computer_use__kill_app: 'Terminate a target application process.',
  computer_use__launch_app: 'Launch an installed application, optionally with startup arguments.',
  computer_use__list_apps: 'List running applications and their process identifiers.',
  computer_use__list_windows: 'List application windows and their identifiers, bounds, and visibility.',
  computer_use__move_cursor: 'Move the pointer to a UI element or coordinate without clicking.',
  computer_use__page: 'Perform a browser page or Chrome DevTools operation against a controlled application.',
  computer_use__press_key: 'Press one or more keyboard keys in a target application.',
  computer_use__replay_trajectory: 'Replay a previously recorded computer-control interaction trajectory.',
  computer_use__right_click: 'Right-click a UI element or coordinate in a target application.',
  computer_use__scroll: 'Scroll a target application window or UI region in the requested direction.',
  computer_use__set_agent_cursor_enabled: 'Enable or disable the visible agent cursor for a computer-control session.',
  computer_use__set_agent_cursor_motion: 'Configure how the visible agent cursor moves between points.',
  computer_use__set_agent_cursor_style: 'Configure the appearance of the visible agent cursor.',
  computer_use__set_config: 'Update supported computer-control driver settings.',
  computer_use__set_value: 'Set the value of an accessible UI control directly.',
  computer_use__start_recording: 'Begin recording computer-control actions as a replayable trajectory.',
  computer_use__start_session: 'Start a named computer-control session and initialize its cursor state.',
  computer_use__stop_recording: 'Stop trajectory recording and return or save the captured actions.',
  computer_use__type_text: 'Type text into a target application or accessible UI element.',
  computer_use__zoom: 'Capture and enlarge a selected region of a target application window.',
};

const TOOL_NAME_ALIASES: Record<string, string> = {
  replace: 'edit',
  search_file_content: 'grep_search',
  task: 'agent',
  bash: 'run_shell_command',
  shell: 'run_shell_command',
  read: 'read_file',
  readfile: 'read_file',
  write: 'write_file',
  writefile: 'write_file',
  grep: 'grep_search',
  searchfiles: 'grep_search',
  findfiles: 'glob',
  listfiles: 'list_directory',
  todowrite: 'todo_write',
  todolist: 'todo_write',
  webfetch: 'web_fetch',
  websearch: 'web_search',
  agent: 'agent',
};

export const UNMAPPED_TOOL_DESCRIPTION =
  'External or custom tool. Use it only when its exact tool name and parameter schema clearly match the task.';

export function getAiAuthoredToolSummary(toolName: string): string | undefined {
  const normalized = toolName.trim().toLowerCase();
  const canonical = TOOL_NAME_ALIASES[normalized] || normalized;
  return AI_AUTHORED_TOOL_SUMMARIES[canonical];
}
